language: node_js
node_js: 
- "12" 
before_install: 
- npm ci 
- sudo apt-get install jq
- npx version-from-git --travis --no-git-tag-version
- git checkout -b temp-ci
- lerna version --force-publish --no-git-tag-version --no-push --yes `cat package.json | jq -r .version`
install: 
- npm run bootstrap
- npm run prepublishOnly
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master
  local-dir: packages/sandbox/build
- provider: script
  script: bash scripts/lerna_publish
  on:
    branch: master
  skip_cleanup: true
- provider: script
  script: bash scripts/lerna_publish
  on:
    tags: true
  skip_cleanup: true
- provider: releases
  api_key: $GITHUB_TOKEN
  on:
    tags: true
  skip_cleanup: true