language: node_js
node_js: 
- "12" 
install: 
- npm ci 
- npm run bootstrap
- npm run prepublishOnly
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on: 
    branch: master
  local-dir: packages/sandbox/build